apiVersion: v1
kind: ConfigMap
metadata:
  name: source-bis-stl-acc-to-ae
  namespace: dbzm-prod
data:
  source-bis-stl-acc-to-ae.json: |-
    {
       "name": "source-bis-stl-acc-to-ae",
       "config": {
          "connector.class": "io.confluent.connect.jdbc.JdbcSourceConnector",
          "connection.url": "jdbc:as400://192.168.1.2;libraries=NFO#DAT",
          "connection.user": "user",
          "connection.password": "password",
          "db.timezone": "Europe/Moscow",
          "dialect.name": "Db2DatabaseDialect",
          "schema.pattern": "NFO#DAT",
          "numeric.mapping": "best_fit",
          "mode": "bulk",
          "poll.interval.ms": "192.168.1.2",
          "table.whitelist": "BISC.NFO#DAT.FCACCHG",
          "topic.prefix": "bis.prod.cdc.",
          "transforms": "AddPrefix",
          "transforms.AddPrefix.type": "org.apache.kafka.connect.transforms.RegexRouter",
          "transforms.AddPrefix.regex": "(.+)",
          "transforms.AddPrefix.replacement": "KFKQ_BIS_STL_ACC_TO_AE_IN"
       }
    }

  .envs: |-
    #{ Dynamic (custom for each connector)
    CONFIG_STORAGE_TOPIC="KFKQ_BIS_STL_ACC_TO_AE_IN_CONFIG"
    OFFSET_STORAGE_TOPIC="KFKQ_BIS_STL_ACC_TO_AE_IN_OFFSET"
    STATUS_STORAGE_TOPIC="KFKQ_BIS_STL_ACC_TO_AE_IN_STATUS"
    GROUP_ID=24
    OFFSET_FLUSH_INTERVAL_MS=1200
    OFFSET_FLUSH_TIMEOUT_MS=2500
    SHUTDOWN_TIMEOUT=2000
    #}

    #{ Static (rarely changed)
    #{ Common part
    REST_HOST_NAME="192.168.1.2"
    ADVERTISED_HOST_NAME="192.168.1.2"
    CONNECT_OFFSET_STORAGE_PARTITIONS=1
    CONNECT_CONFIG_STORAGE_PARTITIONS=1
    CONNECT_STATUS_STORAGE_PARTITIONS=1
    #fixme: option -1 doesn't work for GLAE kafka instead of retail kafka
    CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR=2
    CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR=2
    CONNECT_STATUS_STORAGE_REPLICATION_FACTOR=2
    CONNECT_OFFSET_STORAGE_CLEANUP_POLICY="compact"
    CONNECT_CONFIG_STORAGE_CLEANUP_POLICY="compact"
    CONNECT_STATUS_STORAGE_CLEANUP_POLICY="compact"
      #}

       #{ for GLAE cluster of Kafka
    BOOTSTRAP_SERVERS="servername.domain.department:9092,servername"
    CONNECT_SECURITY_PROTOCOL="PLAINTEXT"
    CONNECT_CONSUMER_SECURITY_PROTOCOL="PLAINTEXT"
    CONNECT_PRODUCER_SECURITY_PROTOCOL="PLAINTEXT"
      #}
    #}

  # only for extra properties that are not in base image's /kafka/config.orig/connect-distributed.properties file
  extra.connect-distributed.properties: |
    # nothing extra (yet)

  log4j.properties: |-
    log4j.rootLogger=INFO, console, gelf

    # Disable excessive reflection warnings - KAFKA-5229
    log4j.logger.org.reflections=ERROR

    log4j.appender.console=org.apache.log4j.ConsoleAppender
    log4j.appender.console.threshold=INFO
    log4j.appender.console.layout=org.apache.log4j.PatternLayout
    log4j.appender.console.layout.ConversionPattern=%d{ISO8601} %-5p  %X{dbz.connectorType}|%X{dbz.connectorName}|%X{dbz.connectorContext}  %m   [%c]%n

    log4j.appender.gelf=biz.paluch.logging.gelf.log4j.GelfLogAppender
    log4j.appender.gelf.Threshold=WARN
    log4j.appender.gelf.Host=udp:mb-cert-log.bank.rrr.department
    log4j.appender.gelf.Port=12201
    log4j.appender.gelf.Version=1.1
    log4j.appender.gelf.Facility=logstash-gelf
    log4j.appender.gelf.ExtractStackTrace=true
    log4j.appender.gelf.FilterStackTrace=true
    log4j.appender.gelf.MdcProfiling=true
    log4j.appender.gelf.IncludeFullMdc=true
    log4j.appender.gelf.AdditionalFields=namespace=dbzm-prod
    log4j.appender.gelf.TimestampPattern=yyyy-MM-dd'T'HH:mm:ss.SSS