apiVersion: v1
kind: ConfigMap
metadata:
  name: source-bis-pitmnt7l
  namespace: dbzm-prod
data:
  sdalluni.pitmnt7l.connector.config.json: |-
    {
       "name": "bisprod.sdalluni.pitmnt7l",
       "config": {
          "connector.class": "io.confluent.connect.jdbc.JdbcSourceConnector",
          "dialect.name": "Db2DatabaseDialect",
          "connection.url": "jdbc:as400://192.168.1.2;libraries=SDALLUNI",
          "connection.user": "user",
          "connection.password": "password",
          "db.timezone": "Europe/Moscow",
          "schema.pattern": "SDALLUNI",
          "table.types": "VIEW",
          "table.whitelist": "BISC.SDALLUNI.PITMNT7L",
          "mode": "timestamp",
          "timestamp.initial": "-1",
          "timestamp.column.name": "SDTMST",
          "numeric.mapping": "best_fit",
          "topic.prefix": "bis.prod.cdc.",
          "transforms": "AddPrefix, ccct",
          "transforms.ccct.type": "org.apache.kafka.connect.transforms.ccct$Value",
          "transforms.ccct.spec": "SDPDAT:int32, SDLUDT:int32, SDLUTM:int32, NTMSGC:int32, NTMSGF:int32, NTMSGT:int32, NTCRD#:string, NTSTAN:int64, NTTDAT:int32, NTTTIM:int32, NTCAID:string, NTCATA:string, NTACC#:string, NTTRN$:int32, NTTRFE:int32, NTCBA$:int32, NTCBAF:int32, NTCBSF:int32, NTCBM$:int32, NTEXDT:int32, NTNAME:string, NTMCAT:int32, NTUSER:string, NTPOSL:int32, NTCZID:string, NTFLID:string, NTRREF:string, SDSAUS:string",
          "transforms.AddPrefix.type": "org.apache.kafka.connect.transforms.RegexRouter",
          "transforms.AddPrefix.regex": "(.+)",
          "transforms.AddPrefix.replacement": "bis.prod.cdc.sdalluni.pitmnt7l"
       }
    }

  sdal_cnl.pitmnt7l.connector.config.json: |-
    {
       "name": "bisprod.sdal_cnl.pitmnt7l",
       "config": {
          "connector.class": "io.confluent.connect.jdbc.JdbcSourceConnector",
          "dialect.name": "Db2DatabaseDialect",
          "connection.url": "jdbc:as400://192.168.1.2;libraries=SDAL_CNL",
          "connection.user": "user",
          "connection.password": "password",
          "db.timezone": "Europe/Moscow",
          "schema.pattern": "SDAL_CNL",
          "table.types": "VIEW",
          "table.whitelist": "BISC.SDAL_CNL.PITMNT7L",
          "mode": "timestamp",
          "timestamp.initial": "-1",
          "timestamp.column.name": "SDTMST",
          "numeric.mapping": "best_fit",
          "topic.prefix": "bis.prod.cdc.",
          "transforms": "AddPrefix, ccct",
          "transforms.ccct.type": "org.apache.kafka.connect.transforms.ccct$Value",
          "transforms.ccct.spec": "SDPDAT:int32, SDLUDT:int32, SDLUTM:int32, NTMSGC:int32, NTMSGF:int32, NTMSGT:int32, NTCRD#:string, NTSTAN:int64, NTTDAT:int32, NTTTIM:int32, NTCAID:string, NTCATA:string, NTACC#:string, NTTRN$:int32, NTTRFE:int32, NTCBA$:int32, NTCBAF:int32, NTCBSF:int32, NTCBM$:int32, NTEXDT:int32, NTNAME:string, NTMCAT:int32, NTUSER:string, NTPOSL:int32, NTCZID:string, NTFLID:string, NTRREF:string, SDSAUS:string",
          "transforms.AddPrefix.type": "org.apache.kafka.connect.transforms.RegexRouter",
          "transforms.AddPrefix.regex": "(.+)",
          "transforms.AddPrefix.replacement": "bis.prod.cdc.sdalcnl.pitmnt7l"
       }
    }
    
  sdal_sbl.pitmnt7l.connector.config.json: |-
    {
       "name": "bisprod.sdal_sbl.pitmnt7l",
       "config": {
          "connector.class": "io.confluent.connect.jdbc.JdbcSourceConnector",
          "dialect.name": "Db2DatabaseDialect",
          "connection.url": "jdbc:as400://192.168.1.2;libraries=SDAL_SBL",
          "connection.user": "user",
          "connection.password": "password",
          "db.timezone": "Europe/Moscow",
          "schema.pattern": "SDAL_SBL",
          "table.types": "VIEW",
          "table.whitelist": "BISC.SDAL_SBL.PITMNT7L",
          "mode": "timestamp",
          "timestamp.initial": "-1",
          "timestamp.column.name": "SDTMST",
          "numeric.mapping": "best_fit",
          "topic.prefix": "bis.prod.cdc.",
          "transforms": "AddPrefix, ccct",
          "transforms.ccct.type": "org.apache.kafka.connect.transforms.ccct$Value",
          "transforms.ccct.spec": "SDPDAT:int32, SDLUDT:int32, SDLUTM:int32, NTMSGC:int32, NTMSGF:int32, NTMSGT:int32, NTCRD#:string, NTSTAN:int64, NTTDAT:int32, NTTTIM:int32, NTCAID:string, NTCATA:string, NTACC#:string, NTTRN$:int32, NTTRFE:int32, NTCBA$:int32, NTCBAF:int32, NTCBSF:int32, NTCBM$:int32, NTEXDT:int32, NTNAME:string, NTMCAT:int32, NTUSER:string, NTPOSL:int32, NTCZID:string, NTFLID:string, NTRREF:string, SDSAUS:string",
          "transforms.AddPrefix.type": "org.apache.kafka.connect.transforms.RegexRouter",
          "transforms.AddPrefix.regex": "(.+)",
          "transforms.AddPrefix.replacement": "bis.prod.cdc.sdalsbl.pitmnt7l"
       }
    }
    
  sdal_zsl.pitmnt7l.connector.config.json: |-
    {
       "name": "bisprod.sdal_zsl.pitmnt7l",
       "config": {
          "connector.class": "io.confluent.connect.jdbc.JdbcSourceConnector",
          "dialect.name": "Db2DatabaseDialect",
          "connection.url": "jdbc:as400://192.168.1.2;libraries=SDAL_ZSL",
          "connection.user": "user",
          "connection.password": "password",
          "db.timezone": "Europe/Moscow",
          "schema.pattern": "SDAL_ZSL",
          "table.types": "VIEW",
          "table.whitelist": "BISC.SDAL_ZSL.PITMNT7L",
          "mode": "timestamp",
          "timestamp.initial": "-1",
          "timestamp.column.name": "SDTMST",
          "numeric.mapping": "best_fit",
          "topic.prefix": "bis.prod.cdc.",
          "transforms": "AddPrefix, ccct",
          "transforms.ccct.type": "org.apache.kafka.connect.transforms.ccct$Value",
          "transforms.ccct.spec": "SDPDAT:int32, SDLUDT:int32, SDLUTM:int32, NTMSGC:int32, NTMSGF:int32, NTMSGT:int32, NTCRD#:string, NTSTAN:int64, NTTDAT:int32, NTTTIM:int32, NTCAID:string, NTCATA:string, NTACC#:string, NTTRN$:int32, NTTRFE:int32, NTCBA$:int32, NTCBAF:int32, NTCBSF:int32, NTCBM$:int32, NTEXDT:int32, NTNAME:string, NTMCAT:int32, NTUSER:string, NTPOSL:int32, NTCZID:string, NTFLID:string, NTRREF:string, SDSAUS:string",
          "transforms.AddPrefix.type": "org.apache.kafka.connect.transforms.RegexRouter",
          "transforms.AddPrefix.regex": "(.+)",
          "transforms.AddPrefix.replacement": "bis.prod.cdc.sdalzsl.pitmnt7l"
       }
    }
    
  sdal_dtl.pitmnt7l.connector.config.json: |-
    {
       "name": "bisprod.sdal_dtl.pitmnt7l",
       "config": {
          "connector.class": "io.confluent.connect.jdbc.JdbcSourceConnector",
          "dialect.name": "Db2DatabaseDialect",
          "connection.url": "jdbc:as400://192.168.1.2;libraries=SDAL_DTL",
          "connection.user": "user",
          "connection.password": "password",
          "db.timezone": "Europe/Moscow",
          "schema.pattern": "SDAL_DTL",
          "table.types": "VIEW",
          "table.whitelist": "BISC.SDAL_DTL.PITMNT7L",
          "mode": "timestamp",
          "timestamp.initial": "-1",
          "timestamp.column.name": "SDTMST",
          "numeric.mapping": "best_fit",
          "topic.prefix": "bis.prod.cdc.",
          "transforms": "AddPrefix, ccct",
          "transforms.ccct.type": "org.apache.kafka.connect.transforms.ccct$Value",
          "transforms.ccct.spec": "SDPDAT:int32, SDLUDT:int32, SDLUTM:int32, NTMSGC:int32, NTMSGF:int32, NTMSGT:int32, NTCRD#:string, NTSTAN:int64, NTTDAT:int32, NTTTIM:int32, NTCAID:string, NTCATA:string, NTACC#:string, NTTRN$:int32, NTTRFE:int32, NTCBA$:int32, NTCBAF:int32, NTCBSF:int32, NTCBM$:int32, NTEXDT:int32, NTNAME:string, NTMCAT:int32, NTUSER:string, NTPOSL:int32, NTCZID:string, NTFLID:string, NTRREF:string, SDSAUS:string",
          "transforms.AddPrefix.type": "org.apache.kafka.connect.transforms.RegexRouter",
          "transforms.AddPrefix.regex": "(.+)",
          "transforms.AddPrefix.replacement": "bis.prod.cdc.sdaldtl.pitmnt7l"
       }
    }

  .envs: |-
    #{ Dynamic (custom for each connector)
    CONFIG_STORAGE_TOPIC="bis.prod.cdct.configs.pitmnt7l"
    OFFSET_STORAGE_TOPIC="bis.prod.cdct.offsets.pitmnt7l"
    STATUS_STORAGE_TOPIC="bis.prod.cdct.statuses.pitmnt7l"
    GROUP_ID=73
    OFFSET_FLUSH_INTERVAL_MS=1200
    OFFSET_FLUSH_TIMEOUT_MS=2500
    SHUTDOWN_TIMEOUT=2000
    #}

    #{ Static (rarely changed)
      #{ Common part
    REST_HOST_NAME="192.168.1.2"
    ADVERTISED_HOST_NAME="192.168.1.2"
    CONNECT_OFFSET_STORAGE_PARTITIONS=1
    CONNECT_CONFIG_STORAGE_PARTITIONS=1
    CONNECT_STATUS_STORAGE_PARTITIONS=1
    CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR=-1
    CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR=-1
    CONNECT_STATUS_STORAGE_REPLICATION_FACTOR=-1
    CONNECT_OFFSET_STORAGE_CLEANUP_POLICY="compact"
    CONNECT_CONFIG_STORAGE_CLEANUP_POLICY="compact"
    CONNECT_STATUS_STORAGE_CLEANUP_POLICY="compact"
      #}

      #{ for retail cluster of Kafka
    BOOTSTRAP_SERVERS="servername.domain.department:9093,servername"
    CONNECT_SECURITY_PROTOCOL="SSL"
    CONNECT_CONSUMER_SECURITY_PROTOCOL="SSL"
    CONNECT_PRODUCER_SECURITY_PROTOCOL="SSL"
    CONNECT_SSL_.rrrTSTORE_LOCATION="/kafka/.ssl/kafka.retail.prod..rrrtstore.jks"
    CONNECT_PRODUCER_SSL_.rrrTSTORE_LOCATION="/kafka/.ssl/kafka.retail.prod..rrrtstore.jks"
    CONNECT_CONSUMER_SSL_.rrrTSTORE_LOCATION="/kafka/.ssl/kafka.retail.prod..rrrtstore.jks"
    CONNECT_SSL_.rrrTSTORE_PASSWORD="password"
    CONNECT_PRODUCER_SSL_.rrrTSTORE_PASSWORD="password"
    CONNECT_CONSUMER_SSL_.rrrTSTORE_PASSWORD="password"
      #}
    #}

  # only for extra properties that are not in base image's /kafka/config.orig/connect-distributed.properties file
  extra.connect-distributed.properties: |
    # nothing extra (yet)

  log4j.properties: |-
    log4j.rootLogger=INFO, console, gelf

    # Disable excessive reflection warnings - KAFKA-5229
    log4j.logger.org.reflections=ERROR

    log4j.appender.console=org.apache.log4j.ConsoleAppender
    log4j.appender.console.threshold=INFO
    log4j.appender.console.layout=org.apache.log4j.PatternLayout
    log4j.appender.console.layout.ConversionPattern=%d{ISO8601} %-5p  %X{dbz.connectorType}|%X{dbz.connectorName}|%X{dbz.connectorContext}  %m   [%c]%n

    log4j.appender.gelf=biz.paluch.logging.gelf.log4j.GelfLogAppender
    log4j.appender.gelf.Threshold=WARN
    log4j.appender.gelf.Host=udp:mbr-log.bank.rrr.department
    log4j.appender.gelf.Port=12201
    log4j.appender.gelf.Version=1.1
    log4j.appender.gelf.Facility=logstash-gelf
    log4j.appender.gelf.ExtractStackTrace=true
    log4j.appender.gelf.FilterStackTrace=true
    log4j.appender.gelf.MdcProfiling=true
    log4j.appender.gelf.IncludeFullMdc=true
    log4j.appender.gelf.AdditionalFields=namespace=dbzm-prod
    log4j.appender.gelf.TimestampPattern=yyyy-MM-dd'T'HH:mm:ss.SSS