apiVersion: v1
kind: ConfigMap
metadata:
  name: source-smscontact
  namespace: dbzm-prod
data:
  source-smscontact.exchange.sms_contact3.connector.config.json: |-
    {
       "name": "smscontact3",
       "config": {
          "dialect.name": "OracleDatabaseDialect",
          "connector.class": "io.confluent.connect.jdbc.JdbcSourceConnector",
          "connection.url": "jdbc:oracle:thin:@(description=(address=(host=192.168.1.2)(protocol=tcp)(port=1521))(connect_data=(service_name=ExchangeP)(server=dedicated)))",
          "connection.user": "user",
          "connection.password": "password",
          "db.timezone": "Europe/Moscow",
          "schema.pattern": "EXCHANGE",
          "query": "SELECT * FROM (SELECT * from database.table_CONTACT WHERE EXCHANGE.SMS_CONTACT.CONTACT_ID >= (SELECT max(CONTACT_ID-1000) from database.table_CONTACT) AND PRIORITY_ORDER = 3 ORDER BY EXCHANGE.SMS_CONTACT.CONTACT_ID ASC)",
          "numeric.mapping": "best_fit",
          "topic.prefix": "rbauto.prod.cdc.",
          "mode": "incrementing",
          "incrementing.column.name": "CONTACT_ID",
          "transforms": "TopicRename",
          "transforms.TopicRename.type": "org.apache.kafka.connect.transforms.RegexRouter",
          "transforms.TopicRename.regex": "(.+)",
          "transforms.TopicRename.replacement": "rbauto.prod.cdc.exchange.smscontact"
       }
    }
    
  source-smscontact.exchange.sms_contact500.connector.config.json: |-
    {
       "name": "smscontact500",
       "config": {
          "dialect.name": "OracleDatabaseDialect",
          "connector.class": "io.confluent.connect.jdbc.JdbcSourceConnector",
          "connection.url": "jdbc:oracle:thin:@(description=(address=(host=192.168.1.2)(protocol=tcp)(port=1521))(connect_data=(service_name=ExchangeP)(server=dedicated)))",
          "connection.user": "user",
          "connection.password": "password",
          "db.timezone": "Europe/Moscow",
          "schema.pattern": "EXCHANGE",
          "query": "SELECT * FROM (SELECT * from database.table_CONTACT WHERE EXCHANGE.SMS_CONTACT.CONTACT_ID >= (SELECT max(CONTACT_ID-192.168.1.2) from database.table_CONTACT) AND PRIORITY_ORDER = 500 ORDER BY EXCHANGE.SMS_CONTACT.CONTACT_ID ASC)",
          "topic.prefix": "rbauto.prod.cdc.",
          "numeric.mapping": "best_fit",
          "mode": "incrementing",
          "incrementing.column.name": "CONTACT_ID",
          "poll.interval.ms": "192.168.1.2",
          "transforms": "TopicRename",
          "transforms.TopicRename.type": "org.apache.kafka.connect.transforms.RegexRouter",
          "transforms.TopicRename.regex": "(.+)",
          "transforms.TopicRename.replacement": "rbauto.prod.cdc.exchange.smscontact"
       }
    }

  .envs: |-
    #{ Dynamic (custom for each connector)
    CONFIG_STORAGE_TOPIC="rbauto.prod.cdct.source.configs.smscontact"
    OFFSET_STORAGE_TOPIC="rbauto.prod.cdct.source.offsets.smscontact"
    STATUS_STORAGE_TOPIC="rbauto.prod.cdct.source.statuses.smscontact"
    GROUP_ID=53
    OFFSET_FLUSH_INTERVAL_MS=1200
    OFFSET_FLUSH_TIMEOUT_MS=2500
    SHUTDOWN_TIMEOUT=2000
    #}

    #{ Static (rarely changed)
      #{ Common part
    REST_HOST_NAME="192.168.1.2"
    ADVERTISED_HOST_NAME="192.168.1.2"
    CONNECT_OFFSET_STORAGE_PARTITIONS=1
    CONNECT_CONFIG_STORAGE_PARTITIONS=1
    CONNECT_STATUS_STORAGE_PARTITIONS=1
    CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR=-1
    CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR=-1
    CONNECT_STATUS_STORAGE_REPLICATION_FACTOR=-1
    CONNECT_OFFSET_STORAGE_CLEANUP_POLICY="compact"
    CONNECT_CONFIG_STORAGE_CLEANUP_POLICY="compact"
    CONNECT_STATUS_STORAGE_CLEANUP_POLICY="compact"
      #}
      
      
      #{ for retail cluster of Kafka
    BOOTSTRAP_SERVERS="servername.domain.department:9093,servername"
    CONNECT_SECURITY_PROTOCOL="SSL"
    CONNECT_CONSUMER_SECURITY_PROTOCOL="SSL"
    CONNECT_PRODUCER_SECURITY_PROTOCOL="SSL"
    CONNECT_SSL_.rrrTSTORE_LOCATION="/kafka/.ssl/kafka.retail.prod..rrrtstore.jks"
    CONNECT_PRODUCER_SSL_.rrrTSTORE_LOCATION="/kafka/.ssl/kafka.retail.prod..rrrtstore.jks"
    CONNECT_CONSUMER_SSL_.rrrTSTORE_LOCATION="/kafka/.ssl/kafka.retail.prod..rrrtstore.jks"
    CONNECT_SSL_.rrrTSTORE_PASSWORD="password"
    CONNECT_PRODUCER_SSL_.rrrTSTORE_PASSWORD="password"
    CONNECT_CONSUMER_SSL_.rrrTSTORE_PASSWORD="password"
      #}
    #}

  # only for extra properties that are not in base image's /kafka/config.orig/connect-distributed.properties file
  extra.connect-distributed.properties: |
    # nothing extra (yet)

  log4j.properties: |-
    log4j.rootLogger=INFO, console, gelf

    # Disable excessive reflection warnings - KAFKA-5229
    log4j.logger.org.reflections=ERROR

    log4j.appender.console=org.apache.log4j.ConsoleAppender
    log4j.appender.console.threshold=INFO
    log4j.appender.console.layout=org.apache.log4j.PatternLayout
    log4j.appender.console.layout.ConversionPattern=%d{ISO8601} %-5p  %X{dbz.connectorType}|%X{dbz.connectorName}|%X{dbz.connectorContext}  %m   [%c]%n

    log4j.appender.gelf=biz.paluch.logging.gelf.log4j.GelfLogAppender
    log4j.appender.gelf.Threshold=WARN
    log4j.appender.gelf.Host=udp:mbr-log.bank.rrr.department
    log4j.appender.gelf.Port=12201
    log4j.appender.gelf.Version=1.1
    log4j.appender.gelf.Facility=logstash-gelf
    log4j.appender.gelf.ExtractStackTrace=true
    log4j.appender.gelf.FilterStackTrace=true
    log4j.appender.gelf.MdcProfiling=true
    log4j.appender.gelf.IncludeFullMdc=true
    log4j.appender.gelf.AdditionalFields=namespace=dbzm-prod
    log4j.appender.gelf.TimestampPattern=yyyy-MM-dd'T'HH:mm:ss.SSS
