kind: Secret
apiVersion: v1
metadata:
  name: kafka-retail-.rrrtstore-jks
  namespace: dbzm-prod
type: Opaque
data:
  # MAYBE needs renaming: kafka.retail.cert -> sg_unipass_ca
  kafka.retail.prod..rrrtstore.jks: >-
    yf1059DXSKc=
